remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: CCIC at EUMETSAT 2023
description: Auxiliary website for poster 5.02
github:
  repository_url: https://github.com/SEE-GEO/ccic
